version: 0.2

phases:
  install:
    runtime-versions:
      docker: 18
  pre_build:
    commands:
      - ls -l
  build:
    commands:
      - mlagents-learn trainer_config.yaml --train --env=3dball
      - ls -l
artifacts:
  files:
    - ./summaries/**/*
    - ./models/**/*